const _classes = {
  base: {
    modal: 'w-full h-full fixed flex flex-col items-center justify-center z-40 top-0 left-0',
    modalScreen: 'w-full h-full opacity-90 bg-stone-800 absolute left-0 top-0',
    modalForm: 'flex flex-col rounded-md shadow-md shadow-slate-900 w-72 absolute opacity-100 z-50',
    modalTitle: 'text-base font-bold px-1 py-2 bg-stone-700 text-neutral-100 rounded-t-md border-b-2 border-b-stone-100',
    button: 'text-lg rounded-md px-2 py-1',
    buttonGroup: 'px-2 py-1 bg-stone-700 text-neutral-50 flex flex-row justify-end gap-2 rounded-b-md',
    colorButton: 'h-4 border-b-2 border-r-2',
    colorGrid: 'grid grid-cols-9 flex-1 mr-2 transition-colors duration-300',
    controlsGroup: 'px-2 py-2 bg-stone-700 text-neutral-50 flex flex-row justify-end gap-2 rounded-b-md',
    iconContainer: 'grid grid-cols-3 gap-2 p-2 overflow-y-scroll h-48 transition-colors duration-300',
    iconLabel: 'flex flex-col justify-center items-center p-2 rounded-full transition-colors duration-300',
    input: 'autofill:text-neutral-100 text-base outline-0 text-neutral-50 w-full px-1 mr-2 transition-colors duration-300',
    inputGroup: 'flex flex-row items-center border-b-2 border-b-stone-100 transition-colors duration-300 w-full max-w-full overflow-hidden',
    label: 'text-neutral-100 text-base font-bold h-8 pr-2 basis-24 shrink-0 grow-0 text-right flex items-center justify-end transition-colors duration-300',
    note: 'text-xs py-1 px-2 text-neutral-900 break-words max-w-full',
    noteButton: 'text-lg font-bold rounded-md my-1 flex-1 border transition-colors',
    notesContainer: 'flex flex-col text-base mr-2 p-1 transition-colors grow shrink basis-px w-full max-w-full',
    notesTextArea: 'my-2 p-1 resize-none transition-colors w-full',
    notesList: 'w-full overflow-hidden list-inside',
    prioButton: 'border basis-4 h-4 peer-checked:basis-12 transition-all',
    prioContainer: 'flex flex-col text-base text-neutral-50 w-full mr-2 px-1 transition-colors',
    prioLabel: 'flex flex-row justify-center items-center relative cursor-pointer',
    select: 'flex-1 text-neutral-100 mr-2 transition-colors',
    warningGroup: 'bg-red-900 text-yellow-300 transition text-center flex flex-row justify-between items-center border-b-2 border-b-stone-100',
    warningImg: 'w-6 h-6 mx-2',
  },
  mixins: {
    peer: 'peer',
    flex1: 'flex-1',
    srOnly: 'sr-only',
    hidden: 'hidden',
    cancel: 'hover:bg-red-800 bg-red-700 text-red-50 border-red-700',
    accept: 'hover:bg-green-800 bg-green-700 text-green-50 border-green-700',
    prioButtons: {
      backgroundColor: {
        high: 'bg-red-500',
        med: 'bg-yellow-500',
        low: 'bg-green-500',
      },
      borderColor: {
        high: 'border-red-300',
        med: 'border-yellow-300',
        low: 'border-green-300',
      }
    },
    colorButton: {
      stone: {backgroundColor: 'bg-stone-500', borderColor: 'border-stone-700'},
      red: {backgroundColor: 'bg-red-500', borderColor: 'border-red-700'},
      orange: {backgroundColor: 'bg-orange-500', borderColor: 'border-orange-700'},
      amber: {backgroundColor: 'bg-amber-500', borderColor: 'border-amber-700'},
      yellow: {backgroundColor: 'bg-yellow-500', borderColor: 'border-yellow-700'},
      lime: {backgroundColor: 'bg-lime-500', borderColor: 'border-lime-700'},
      green: {backgroundColor: 'bg-green-500', borderColor: 'border-green-700'},
      emerald: {backgroundColor: 'bg-emerald-500', borderColor: 'border-emerald-700'},
      teal: {backgroundColor: 'bg-teal-500', borderColor: 'border-teal-700'},
      rose: {backgroundColor: 'bg-rose-500', borderColor: 'border-rose-700'},
      pink: {backgroundColor: 'bg-pink-500', borderColor: 'border-pink-700'},
      fuchsia: {backgroundColor: 'bg-fuchsia-500', borderColor: 'border-fuchsia-700'},
      purple: {backgroundColor: 'bg-purple-500', borderColor: 'border-purple-700'},
      violet: {backgroundColor: 'bg-violet-500', borderColor: 'border-violet-700'},
      indigo: {backgroundColor: 'bg-indigo-500', borderColor: 'border-indigo-700'},
      blue: {backgroundColor: 'bg-blue-500', borderColor: 'border-blue-700'},
      sky: {backgroundColor: 'bg-sky-500', borderColor: 'border-sky-700'},
      cyan: {backgroundColor: 'bg-cyan-500', borderColor: 'border-cyan-700'},
    },
    notesTextAreaTextColor: {
      stone: 'text-stone-900',
      red: 'text-red-900',
      orange: 'text-orange-900',
      amber: 'text-amber-900',
      yellow: 'text-yellow-900',
      lime: 'text-lime-900',
      green: 'text-green-900',
      emerald: 'text-emerald-900',
      teal: 'text-teal-900',
      rose: 'text-rose-900',
      pink: 'text-pink-900',
      fuchsia: 'text-fuchsia-900',
      purple: 'text-purple-900',
      violet: 'text-violet-900',
      indigo: 'text-indigo-900',
      blue: 'text-blue-900',
      sky: 'text-sky-900',
      cyan: 'text-cyan-900',
    }
  },
  animations: {
    fadeIn: 'animate-fadeIn',
    fadeOut: 'animate-fadeOut',
    slideInTop: 'animate-slideInTop',
    slideInRight: 'animate-slideInRight',
    slideInBottom: 'animate-slideInBottom',
    slideInLeft: 'animate-slideInLeft',
    slideOutTop: 'animate-slideOutTop',
    slideOutRight: 'animate-slideOutRight',
    slideOutBottom: 'animate-slideOutBottom',
    slideOutLeft: 'animate-slideOutLeft',
  }
}
export default _classes;